[api]
apiKeyR = ""                                    # 蜜罐信息apiKey
apiQSecretR = ""                                # 蜜罐信息apiSec (通过 apikeyX 和apiSecretX 可通过接口获取 AccessToken)

[mysql]
file = "/etc/hosts,/etc/hosts,/etc/issue"        # 上钩后获取的攻击者信息
addr = "0.0.0.0:3306"

[ssh]
addr = "0.0.0.0:22"
prefix = "[root@ubuntu ~]#"

[http]
addr = "0.0.0.0:8081"
msg = "Hello world!"

[redis]
addr = "0.0.0.0:6379"
