[rpc]
status = 0                                      # 模式 0关闭 1服务端 2客户端
addr = "0.0.0.0:7777"                           # RPC 服务端地址 or 客户端地址
name = "Server"                                 # 状态1 服务端 名称 状态2 客户端 名称

[api]
apiKeyR = ""                                    # 蜜罐信息上报apiKey
apiQSecretR = ""                                # 蜜罐信息上报apiSec (通过 apikeyX 和apiSecretX 可通过接口获取 AccessTokenX 用作
apiKeyQ = ""                                    # 蜜罐信息查询apiKey
apiSecretQ = ""                                 # 蜜罐信息查询apiSec